# https://github.com/pkgcore/pkgcheck-action#example-workflows
name: pkgcheck

on:
  push:
  pull_request:
  workflow_dispatch: # allow manual trigger
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

      # Workaround runner failures on python-3.12:
      #   https://github.com/pkgcore/pkgcheck-action/issues/13
    - name: Pin python to 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run pkgcheck
      uses: pkgcore/pkgcheck-action@v1
